AWSTemplateFormatVersion: "2010-09-09"
Description: Template for rHealth Workflow roles and policies in Development

#----------------------------------------------------PARAMETERS----------------------------------------------------------------
#Parameters:
    
#-----------------------------------------------------RESOURCES---------------------------------------------------------------

Resources:
  rHealthWorkflowGlueToAccessS3CloudwatchlogsDev:
    Type: AWS::IAM::Role
    Properties:
      Description: Role used by Glue for the rHealth workflow in development.
      Path: '/'
      RoleName: rhealth-etl-dev-workflow-dev
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Tags:
       - Key: Environment
         Value: rhealth-etl-dev
